using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Text;

namespace SDSFoundation.Model.Schedule.NetStandard.Enumerations
{
    /// <summary>
    /// Use extension method to get the string value:   public static string ToDescriptionString(this Timezones val)
    /// https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#Legend
    /// </summary>
    public enum Timezones
    {
        [Description("Default Timezone")]
        None,
        [Description("Africa/Abidjan")]
        Africa_Abidjan,
        [Description("Africa/Accra")]
        Africa_Accra,
        [Description("Africa/Addis_Ababa")]
        Africa_Addis_Ababa,
        [Description("Africa/Algiers")]
        Africa_Algiers,
        [Description("Africa/Asmara")]
        Africa_Asmara,
        [Description("Africa/Bamako")]
        Africa_Bamako,
        [Description("Africa/Bangui")]
        Africa_Bangui,
        [Description("Africa/Banjul")]
        Africa_Banjul,
        [Description("Africa/Bissau")]
        Africa_Bissau,
        [Description("Africa/Blantyre")]
        Africa_Blantyre,
        [Description("Africa/Brazzaville")]
        Africa_Brazzaville,
        [Description("Africa/Bujumbura")]
        Africa_Bujumbura,
        [Description("Africa/Cairo")]
        Africa_Cairo,
        [Description("Africa/Casablanca")]
        Africa_Casablanca,
        [Description("Africa/Ceuta")]
        Africa_Ceuta,
        [Description("Africa/Conakry")]
        Africa_Conakry,
        [Description("Africa/Dakar")]
        Africa_Dakar,
        [Description("Africa/Dar_es_Salaam")]
        Africa_Dar_es_Salaam,
        [Description("Africa/Djibouti")]
        Africa_Djibouti,
        [Description("Africa/Douala")]
        Africa_Douala,
        [Description("Africa/El_Aaiun")]
        Africa_El_Aaiun,
        [Description("Africa/Freetown")]
        Africa_Freetown,
        [Description("Africa/Gaborone")]
        Africa_Gaborone,
        [Description("Africa/Harare")]
        Africa_Harare,
        [Description("Africa/Johannesburg")]
        Africa_Johannesburg,
        [Description("Africa/Juba")]
        Africa_Juba,
        [Description("Africa/Kampala")]
        Africa_Kampala,
        [Description("Africa/Khartoum")]
        Africa_Khartoum,
        [Description("Africa/Kigali")]
        Africa_Kigali,
        [Description("Africa/Kinshasa")]
        Africa_Kinshasa,
        [Description("Africa/Lagos")]
        Africa_Lagos,
        [Description("Africa/Libreville")]
        Africa_Libreville,
        [Description("Africa/Lome")]
        Africa_Lome,
        [Description("Africa/Luanda")]
        Africa_Luanda,
        [Description("Africa/Lubumbashi")]
        Africa_Lubumbashi,
        [Description("Africa/Lusaka")]
        Africa_Lusaka,
        [Description("Africa/Malabo")]
        Africa_Malabo,
        [Description("Africa/Maputo")]
        Africa_Maputo,
        [Description("Africa/Maseru")]
        Africa_Maseru,
        [Description("Africa/Mbabane")]
        Africa_Mbabane,
        [Description("Africa/Mogadishu")]
        Africa_Mogadishu,
        [Description("Africa/Monrovia")]
        Africa_Monrovia,
        [Description("Africa/Nairobi")]
        Africa_Nairobi,
        [Description("Africa/Ndjamena")]
        Africa_Ndjamena,
        [Description("Africa/Niamey")]
        Africa_Niamey,
        [Description("Africa/Nouakchott")]
        Africa_Nouakchott,
        [Description("Africa/Ouagadougou")]
        Africa_Ouagadougou,
        [Description("Africa/Porto-Novo")]
        Africa_Porto_Novo,
        [Description("Africa/Sao_Tome")]
        Africa_Sao_Tome,
        [Description("Africa/Timbuktu")]
        Africa_Timbuktu,
        [Description("Africa/Tripoli")]
        Africa_Tripoli,
        [Description("Africa/Tunis")]
        Africa_Tunis,
        [Description("Africa/Windhoek")]
        Africa_Windhoek,
        [Description("America/Adak")]
        America_Adak,
        [Description("America/Anchorage")]
        America_Anchorage,
        [Description("America/Anguilla")]
        America_Anguilla,
        [Description("America/Antigua")]
        America_Antigua,
        [Description("America/Araguaina")]
        America_Araguaina,
        [Description("America/Argentina/Buenos_Aires")]
        America_Argentina_Buenos_Aires,
        [Description("America/Argentina/Catamarca")]
        America_Argentina_Catamarca,
        [Description("America/Argentina/ComodRivadavia")]
        America_Argentina_ComodRivadavia,
        [Description("America/Argentina/Cordoba")]
        America_Argentina_Cordoba,
        [Description("America/Argentina/Jujuy")]
        America_Argentina_Jujuy,
        [Description("America/Argentina/La_Rioja")]
        America_Argentina_La_Rioja,
        [Description("America/Argentina/Mendoza")]
        America_Argentina_Mendoza,
        [Description("America/Argentina/Rio_Gallegos")]
        America_Argentina_Rio_Gallegos,
        [Description("America/Argentina/Salta")]
        America_Argentina_Salta,
        [Description("America/Argentina/San_Juan")]
        America_Argentina_San_Juan,
        [Description("America/Argentina/San_Luis")]
        America_Argentina_San_Luis,
        [Description("America/Argentina/Tucuman")]
        America_Argentina_Tucuman,
        [Description("America/Argentina/Ushuaia")]
        America_Argentina_Ushuaia,
        [Description("America/Aruba")]
        America_Aruba,
        [Description("America/Asuncion")]
        America_Asuncion,
        [Description("America/Atikokan")]
        America_Atikokan,
        [Description("America/Atka")]
        America_Atka,
        [Description("America/Bahia")]
        America_Bahia,
        [Description("America/Bahia_Banderas")]
        America_Bahia_Banderas,
        [Description("America/Barbados")]
        America_Barbados,
        [Description("America/Belem")]
        America_Belem,
        [Description("America/Belize")]
        America_Belize,
        [Description("America/Blanc-Sablon")]
        America_Blanc_Sablon,
        [Description("America/Boa_Vista")]
        America_Boa_Vista,
        [Description("America/Bogota")]
        America_Bogota,
        [Description("America/Boise")]
        America_Boise,
        [Description("America/Buenos_Aires")]
        America_Buenos_Aires,
        [Description("America/Cambridge_Bay")]
        America_Cambridge_Bay,
        [Description("America/Campo_Grande")]
        America_Campo_Grande,
        [Description("America/Cancun")]
        America_Cancun,
        [Description("America/Caracas")]
        America_Caracas,
        [Description("America/Catamarca")]
        America_Catamarca,
        [Description("America/Cayenne")]
        America_Cayenne,
        [Description("America/Cayman")]
        America_Cayman,
        [Description("America/Chicago")]
        America_Chicago,
        [Description("America/Chihuahua")]
        America_Chihuahua,
        [Description("America/Coral_Harbour")]
        America_Coral_Harbour,
        [Description("America/Cordoba")]
        America_Cordoba,
        [Description("America/Costa_Rica")]
        America_Costa_Rica,
        [Description("America/Creston")]
        America_Creston,
        [Description("America/Cuiaba")]
        America_Cuiaba,
        [Description("America/Curacao")]
        America_Curacao,
        [Description("America/Danmarkshavn")]
        America_Danmarkshavn,
        [Description("America/Dawson")]
        America_Dawson,
        [Description("America/Dawson_Creek")]
        America_Dawson_Creek,
        [Description("America/Denver")]
        America_Denver,
        [Description("America/Detroit")]
        America_Detroit,
        [Description("America/Dominica")]
        America_Dominica,
        [Description("America/Edmonton")]
        America_Edmonton,
        [Description("America/Eirunepe")]
        America_Eirunepe,
        [Description("America/El_Salvador")]
        America_El_Salvador,
        [Description("America/Ensenada")]
        America_Ensenada,
        [Description("America/Fort_Nelson")]
        America_Fort_Nelson,
        [Description("America/Fort_Wayne")]
        America_Fort_Wayne,
        [Description("America/Fortaleza")]
        America_Fortaleza,
        [Description("America/Glace_Bay")]
        America_Glace_Bay,
        [Description("America/Godthab")]
        America_Godthab,
        [Description("America/Goose_Bay")]
        America_Goose_Bay,
        [Description("America/Grand_Turk")]
        America_Grand_Turk,
        [Description("America/Grenada")]
        America_Grenada,
        [Description("America/Guadeloupe")]
        America_Guadeloupe,
        [Description("America/Guatemala")]
        America_Guatemala,
        [Description("America/Guayaquil")]
        America_Guayaquil,
        [Description("America/Guyana")]
        America_Guyana,
        [Description("America/Halifax")]
        America_Halifax,
        [Description("America/Havana")]
        America_Havana,
        [Description("America/Hermosillo")]
        America_Hermosillo,
        [Description("America/Indiana/Indianapolis")]
        America_Indiana_Indianapolis,
        [Description("America/Indiana/Knox")]
        America_Indiana_Knox,
        [Description("America/Indiana/Marengo")]
        America_Indiana_Marengo,
        [Description("America/Indiana/Petersburg")]
        America_Indiana_Petersburg,
        [Description("America/Indiana/Tell_City")]
        America_Indiana_Tell_City,
        [Description("America/Indiana/Vevay")]
        America_Indiana_Vevay,
        [Description("America/Indiana/Vincennes")]
        America_Indiana_Vincennes,
        [Description("America/Indiana/Winamac")]
        America_Indiana_Winamac,
        [Description("America/Indianapolis")]
        America_Indianapolis,
        [Description("America/Inuvik")]
        America_Inuvik,
        [Description("America/Iqaluit")]
        America_Iqaluit,
        [Description("America/Jamaica")]
        America_Jamaica,
        [Description("America/Jujuy")]
        America_Jujuy,
        [Description("America/Juneau")]
        America_Juneau,
        [Description("America/Kentucky/Louisville")]
        America_Kentucky_Louisville,
        [Description("America/Kentucky/Monticello")]
        America_Kentucky_Monticello,
        [Description("America/Knox_IN")]
        America_Knox_IN,
        [Description("America/Kralendijk")]
        America_Kralendijk,
        [Description("America/La_Paz")]
        America_La_Paz,
        [Description("America/Lima")]
        America_Lima,
        [Description("America/Los_Angeles")]
        America_Los_Angeles,
        [Description("America/Louisville")]
        America_Louisville,
        [Description("America/Lower_Princes")]
        America_Lower_Princes,
        [Description("America/Maceio")]
        America_Maceio,
        [Description("America/Managua")]
        America_Managua,
        [Description("America/Manaus")]
        America_Manaus,
        [Description("America/Marigot")]
        America_Marigot,
        [Description("America/Martinique")]
        America_Martinique,
        [Description("America/Matamoros")]
        America_Matamoros,
        [Description("America/Mazatlan")]
        America_Mazatlan,
        [Description("America/Mendoza")]
        America_Mendoza,
        [Description("America/Menominee")]
        America_Menominee,
        [Description("America/Merida")]
        America_Merida,
        [Description("America/Metlakatla")]
        America_Metlakatla,
        [Description("America/Mexico_City")]
        America_Mexico_City,
        [Description("America/Miquelon")]
        America_Miquelon,
        [Description("America/Moncton")]
        America_Moncton,
        [Description("America/Monterrey")]
        America_Monterrey,
        [Description("America/Montevideo")]
        America_Montevideo,
        [Description("America/Montreal")]
        America_Montreal,
        [Description("America/Montserrat")]
        America_Montserrat,
        [Description("America/Nassau")]
        America_Nassau,
        [Description("America/New_York")]
        America_New_York,
        [Description("America/Nipigon")]
        America_Nipigon,
        [Description("America/Nome")]
        America_Nome,
        [Description("America/Noronha")]
        America_Noronha,
        [Description("America/North_Dakota/Beulah")]
        America_North_Dakota_Beulah,
        [Description("America/North_Dakota/Center")]
        America_North_Dakota_Center,
        [Description("America/North_Dakota/New_Salem")]
        America_North_Dakota_New_Salem,
        [Description("America/Ojinaga")]
        America_Ojinaga,
        [Description("America/Panama")]
        America_Panama,
        [Description("America/Pangnirtung")]
        America_Pangnirtung,
        [Description("America/Paramaribo")]
        America_Paramaribo,
        [Description("America/Phoenix")]
        America_Phoenix,
        [Description("America/Port-au-Prince")]
        America_Port_au_Prince,
        [Description("America/Port_of_Spain")]
        America_Port_of_Spain,
        [Description("America/Porto_Acre")]
        America_Porto_Acre,
        [Description("America/Porto_Velho")]
        America_Porto_Velho,
        [Description("America/Puerto_Rico")]
        America_Puerto_Rico,
        [Description("America/Punta_Arenas")]
        America_Punta_Arenas,
        [Description("America/Rainy_River")]
        America_Rainy_River,
        [Description("America/Rankin_Inlet")]
        America_Rankin_Inlet,
        [Description("America/Recife")]
        America_Recife,
        [Description("America/Regina")]
        America_Regina,
        [Description("America/Resolute")]
        America_Resolute,
        [Description("America/Rio_Branco")]
        America_Rio_Branco,
        [Description("America/Rosario")]
        America_Rosario,
        [Description("America/Santa_Isabel")]
        America_Santa_Isabel,
        [Description("America/Santarem")]
        America_Santarem,
        [Description("America/Santiago")]
        America_Santiago,
        [Description("America/Santo_Domingo")]
        America_Santo_Domingo,
        [Description("America/Sao_Paulo")]
        America_Sao_Paulo,
        [Description("America/Scoresbysund")]
        America_Scoresbysund,
        [Description("America/Shiprock")]
        America_Shiprock,
        [Description("America/Sitka")]
        America_Sitka,
        [Description("America/St_Barthelemy")]
        America_St_Barthelemy,
        [Description("America/St_Johns")]
        America_St_Johns,
        [Description("America/St_Kitts")]
        America_St_Kitts,
        [Description("America/St_Lucia")]
        America_St_Lucia,
        [Description("America/St_Thomas")]
        America_St_Thomas,
        [Description("America/St_Vincent")]
        America_St_Vincent,
        [Description("America/Swift_Current")]
        America_Swift_Current,
        [Description("America/Tegucigalpa")]
        America_Tegucigalpa,
        [Description("America/Thule")]
        America_Thule,
        [Description("America/Thunder_Bay")]
        America_Thunder_Bay,
        [Description("America/Tijuana")]
        America_Tijuana,
        [Description("America/Toronto")]
        America_Toronto,
        [Description("America/Tortola")]
        America_Tortola,
        [Description("America/Vancouver")]
        America_Vancouver,
        [Description("America/Virgin")]
        America_Virgin,
        [Description("America/Whitehorse")]
        America_Whitehorse,
        [Description("America/Winnipeg")]
        America_Winnipeg,
        [Description("America/Yakutat")]
        America_Yakutat,
        [Description("America/Yellowknife")]
        America_Yellowknife,
        [Description("Antarctica/Casey")]
        Antarctica_Casey,
        [Description("Antarctica/Davis")]
        Antarctica_Davis,
        [Description("Antarctica/DumontDUrville")]
        Antarctica_DumontDUrville,
        [Description("Antarctica/Macquarie")]
        Antarctica_Macquarie,
        [Description("Antarctica/Mawson")]
        Antarctica_Mawson,
        [Description("Antarctica/McMurdo")]
        Antarctica_McMurdo,
        [Description("Antarctica/Palmer")]
        Antarctica_Palmer,
        [Description("Antarctica/Rothera")]
        Antarctica_Rothera,
        [Description("Antarctica/South_Pole")]
        Antarctica_South_Pole,
        [Description("Antarctica/Syowa")]
        Antarctica_Syowa,
        [Description("Antarctica/Troll")]
        Antarctica_Troll,
        [Description("Antarctica/Vostok")]
        Antarctica_Vostok,
        [Description("Arctic/Longyearbyen")]
        Arctic_Longyearbyen,
        [Description("Asia/Aden")]
        Asia_Aden,
        [Description("Asia/Almaty")]
        Asia_Almaty,
        [Description("Asia/Amman")]
        Asia_Amman,
        [Description("Asia/Anadyr")]
        Asia_Anadyr,
        [Description("Asia/Aqtau")]
        Asia_Aqtau,
        [Description("Asia/Aqtobe")]
        Asia_Aqtobe,
        [Description("Asia/Ashgabat")]
        Asia_Ashgabat,
        [Description("Asia/Ashkhabad")]
        Asia_Ashkhabad,
        [Description("Asia/Atyrau")]
        Asia_Atyrau,
        [Description("Asia/Baghdad")]
        Asia_Baghdad,
        [Description("Asia/Bahrain")]
        Asia_Bahrain,
        [Description("Asia/Baku")]
        Asia_Baku,
        [Description("Asia/Bangkok")]
        Asia_Bangkok,
        [Description("Asia/Barnaul")]
        Asia_Barnaul,
        [Description("Asia/Beirut")]
        Asia_Beirut,
        [Description("Asia/Bishkek")]
        Asia_Bishkek,
        [Description("Asia/Brunei")]
        Asia_Brunei,
        [Description("Asia/Calcutta")]
        Asia_Calcutta,
        [Description("Asia/Chita")]
        Asia_Chita,
        [Description("Asia/Choibalsan")]
        Asia_Choibalsan,
        [Description("Asia/Chongqing")]
        Asia_Chongqing,
        [Description("Asia/Chungking")]
        Asia_Chungking,
        [Description("Asia/Colombo")]
        Asia_Colombo,
        [Description("Asia/Dacca")]
        Asia_Dacca,
        [Description("Asia/Damascus")]
        Asia_Damascus,
        [Description("Asia/Dhaka")]
        Asia_Dhaka,
        [Description("Asia/Dili")]
        Asia_Dili,
        [Description("Asia/Dubai")]
        Asia_Dubai,
        [Description("Asia/Dushanbe")]
        Asia_Dushanbe,
        [Description("Asia/Famagusta")]
        Asia_Famagusta,
        [Description("Asia/Gaza")]
        Asia_Gaza,
        [Description("Asia/Harbin")]
        Asia_Harbin,
        [Description("Asia/Hebron")]
        Asia_Hebron,
        [Description("Asia/Ho_Chi_Minh")]
        Asia_Ho_Chi_Minh,
        [Description("Asia/Hong_Kong")]
        Asia_Hong_Kong,
        [Description("Asia/Hovd")]
        Asia_Hovd,
        [Description("Asia/Irkutsk")]
        Asia_Irkutsk,
        [Description("Asia/Istanbul")]
        Asia_Istanbul,
        [Description("Asia/Jakarta")]
        Asia_Jakarta,
        [Description("Asia/Jayapura")]
        Asia_Jayapura,
        [Description("Asia/Jerusalem")]
        Asia_Jerusalem,
        [Description("Asia/Kabul")]
        Asia_Kabul,
        [Description("Asia/Kamchatka")]
        Asia_Kamchatka,
        [Description("Asia/Karachi")]
        Asia_Karachi,
        [Description("Asia/Kashgar")]
        Asia_Kashgar,
        [Description("Asia/Kathmandu")]
        Asia_Kathmandu,
        [Description("Asia/Katmandu")]
        Asia_Katmandu,
        [Description("Asia/Khandyga")]
        Asia_Khandyga,
        [Description("Asia/Kolkata")]
        Asia_Kolkata,
        [Description("Asia/Krasnoyarsk")]
        Asia_Krasnoyarsk,
        [Description("Asia/Kuala_Lumpur")]
        Asia_Kuala_Lumpur,
        [Description("Asia/Kuching")]
        Asia_Kuching,
        [Description("Asia/Kuwait")]
        Asia_Kuwait,
        [Description("Asia/Macao")]
        Asia_Macao,
        [Description("Asia/Macau")]
        Asia_Macau,
        [Description("Asia/Magadan")]
        Asia_Magadan,
        [Description("Asia/Makassar")]
        Asia_Makassar,
        [Description("Asia/Manila")]
        Asia_Manila,
        [Description("Asia/Muscat")]
        Asia_Muscat,
        [Description("Asia/Novokuznetsk")]
        Asia_Novokuznetsk,
        [Description("Asia/Novosibirsk")]
        Asia_Novosibirsk,
        [Description("Asia/Omsk")]
        Asia_Omsk,
        [Description("Asia/Oral")]
        Asia_Oral,
        [Description("Asia/Phnom_Penh")]
        Asia_Phnom_Penh,
        [Description("Asia/Pontianak")]
        Asia_Pontianak,
        [Description("Asia/Pyongyang")]
        Asia_Pyongyang,
        [Description("Asia/Qatar")]
        Asia_Qatar,
        [Description("Asia/Qyzylorda")]
        Asia_Qyzylorda,
        [Description("Asia/Rangoon")]
        Asia_Rangoon,
        [Description("Asia/Riyadh")]
        Asia_Riyadh,
        [Description("Asia/Saigon")]
        Asia_Saigon,
        [Description("Asia/Sakhalin")]
        Asia_Sakhalin,
        [Description("Asia/Samarkand")]
        Asia_Samarkand,
        [Description("Asia/Seoul")]
        Asia_Seoul,
        [Description("Asia/Shanghai")]
        Asia_Shanghai,
        [Description("Asia/Singapore")]
        Asia_Singapore,
        [Description("Asia/Srednekolymsk")]
        Asia_Srednekolymsk,
        [Description("Asia/Taipei")]
        Asia_Taipei,
        [Description("Asia/Tashkent")]
        Asia_Tashkent,
        [Description("Asia/Tbilisi")]
        Asia_Tbilisi,
        [Description("Asia/Tehran")]
        Asia_Tehran,
        [Description("Asia/Tel_Aviv")]
        Asia_Tel_Aviv,
        [Description("Asia/Thimbu")]
        Asia_Thimbu,
        [Description("Asia/Thimphu")]
        Asia_Thimphu,
        [Description("Asia/Tokyo")]
        Asia_Tokyo,
        [Description("Asia/Tomsk")]
        Asia_Tomsk,
        [Description("Asia/Ujung_Pandang")]
        Asia_Ujung_Pandang,
        [Description("Asia/Ulaanbaatar")]
        Asia_Ulaanbaatar,
        [Description("Asia/Ulan_Bator")]
        Asia_Ulan_Bator,
        [Description("Asia/Urumqi")]
        Asia_Urumqi,
        [Description("Asia/Ust-Nera")]
        Asia_Ust_Nera,
        [Description("Asia/Vientiane")]
        Asia_Vientiane,
        [Description("Asia/Vladivostok")]
        Asia_Vladivostok,
        [Description("Asia/Yakutsk")]
        Asia_Yakutsk,
        [Description("Asia/Yangon")]
        Asia_Yangon,
        [Description("Asia/Yekaterinburg")]
        Asia_Yekaterinburg,
        [Description("Asia/Yerevan")]
        Asia_Yerevan,
        [Description("Atlantic/Azores")]
        Atlantic_Azores,
        [Description("Atlantic/Bermuda")]
        Atlantic_Bermuda,
        [Description("Atlantic/Canary")]
        Atlantic_Canary,
        [Description("Atlantic/Cape_Verde")]
        Atlantic_Cape_Verde,
        [Description("Atlantic/Faeroe")]
        Atlantic_Faeroe,
        [Description("Atlantic/Faroe")]
        Atlantic_Faroe,
        [Description("Atlantic/Jan_Mayen")]
        Atlantic_Jan_Mayen,
        [Description("Atlantic/Madeira")]
        Atlantic_Madeira,
        [Description("Atlantic/Reykjavik")]
        Atlantic_Reykjavik,
        [Description("Atlantic/South_Georgia")]
        Atlantic_South_Georgia,
        [Description("Atlantic/St_Helena")]
        Atlantic_St_Helena,
        [Description("Atlantic/Stanley")]
        Atlantic_Stanley,
        [Description("Australia/Adelaide")]
        Australia_Adelaide,
        [Description("Australia/Brisbane")]
        Australia_Brisbane,
        [Description("Australia/Broken_Hill")]
        Australia_Broken_Hill,
        [Description("Australia/Canberra")]
        Australia_Canberra,
        [Description("Australia/Currie")]
        Australia_Currie,
        [Description("Australia/Darwin")]
        Australia_Darwin,
        [Description("Australia/Eucla")]
        Australia_Eucla,
        [Description("Australia/Hobart")]
        Australia_Hobart,
        [Description("Australia/Lindeman")]
        Australia_Lindeman,
        [Description("Australia/Lord_Howe")]
        Australia_Lord_Howe,
        [Description("Australia/Melbourne")]
        Australia_Melbourne,
        [Description("Australia/Perth")]
        Australia_Perth,
        [Description("Australia/Sydney")]
        Australia_Sydney,
        [Description("Australia/Yancowinna")]
        Australia_Yancowinna,
        [Description("Etc/GMT")]
        Etc_GMT,
        [Description("Etc/GMT+0")]
        Etc_GMT_Plus_0,
        [Description("Etc/GMT+1")]
        Etc_GMT_Plus_1,
        [Description("Etc/GMT+10")]
        Etc_GMT_Plus_10,
        [Description("Etc/GMT+11")]
        Etc_GMT_Plus_11,
        [Description("Etc/GMT+12")]
        Etc_GMT_Plus_12,
        [Description("Etc/GMT+2")]
        Etc_GMT_Plus_2,
        [Description("Etc/GMT+3")]
        Etc_GMT_Plus_3,
        [Description("Etc/GMT+4")]
        Etc_GMT_Plus_4,
        [Description("Etc/GMT+5")]
        Etc_GMT_Plus_5,
        [Description("Etc/GMT+6")]
        Etc_GMT_Plus_6,
        [Description("Etc/GMT+7")]
        Etc_GMT_Plus_7,
        [Description("Etc/GMT+8")]
        Etc_GMT_Plus_8,
        [Description("Etc/GMT+9")]
        Etc_GMT_Plus_9,
        [Description("Etc/GMT-0")]
        Etc_GMT_Minus_0,
        [Description("Etc/GMT-1")]
        Etc_GMT_Minus_1,
        [Description("Etc/GMT-10")]
        Etc_GMT_Minus_10,
        [Description("Etc/GMT-11")]
        Etc_GMT_Minus_11,
        [Description("Etc/GMT-12")]
        Etc_GMT_Minus_12,
        [Description("Etc/GMT-13")]
        Etc_GMT_Minus_13,
        [Description("Etc/GMT-14")]
        Etc_GMT_Minus_14,
        [Description("Etc/GMT-2")]
        Etc_GMT_Minus_2,
        [Description("Etc/GMT-3")]
        Etc_GMT_Minus_3,
        [Description("Etc/GMT-4")]
        Etc_GMT_Minus_4,
        [Description("Etc/GMT-5")]
        Etc_GMT_Minus_5,
        [Description("Etc/GMT-6")]
        Etc_GMT_Minus_6,
        [Description("Etc/GMT-7")]
        Etc_GMT_Minus_7,
        [Description("Etc/GMT-8")]
        Etc_GMT_Minus_8,
        [Description("Etc/GMT-9")]
        Etc_GMT_Minus_9,
        [Description("Etc/GMT0")]
        Etc_GMT0,
        [Description("Etc/UTC")]
        Etc_UTC,
        [Description("Europe/Amsterdam")]
        Europe_Amsterdam,
        [Description("Europe/Andorra")]
        Europe_Andorra,
        [Description("Europe/Astrakhan")]
        Europe_Astrakhan,
        [Description("Europe/Athens")]
        Europe_Athens,
        [Description("Europe/Belfast")]
        Europe_Belfast,
        [Description("Europe/Belgrade")]
        Europe_Belgrade,
        [Description("Europe/Berlin")]
        Europe_Berlin,
        [Description("Europe/Bratislava")]
        Europe_Bratislava,
        [Description("Europe/Brussels")]
        Europe_Brussels,
        [Description("Europe/Bucharest")]
        Europe_Bucharest,
        [Description("Europe/Budapest")]
        Europe_Budapest,
        [Description("Europe/Busingen")]
        Europe_Busingen,
        [Description("Europe/Chisinau")]
        Europe_Chisinau,
        [Description("Europe/Copenhagen")]
        Europe_Copenhagen,
        [Description("Europe/Dublin")]
        Europe_Dublin,
        [Description("Europe/Gibraltar")]
        Europe_Gibraltar,
        [Description("Europe/Guernsey")]
        Europe_Guernsey,
        [Description("Europe/Helsinki")]
        Europe_Helsinki,
        [Description("Europe/Isle_of_Man")]
        Europe_Isle_of_Man,
        [Description("Europe/Istanbul")]
        Europe_Istanbul,
        [Description("Europe/Jersey")]
        Europe_Jersey,
        [Description("Europe/Kaliningrad")]
        Europe_Kaliningrad,
        [Description("Europe/Kiev")]
        Europe_Kiev,
        [Description("Europe/Kirov")]
        Europe_Kirov,
        [Description("Europe/Lisbon")]
        Europe_Lisbon,
        [Description("Europe/Ljubljana")]
        Europe_Ljubljana,
        [Description("Europe/London")]
        Europe_London,
        [Description("Europe/Luxembourg")]
        Europe_Luxembourg,
        [Description("Europe/Madrid")]
        Europe_Madrid,
        [Description("Europe/Malta")]
        Europe_Malta,
        [Description("Europe/Mariehamn")]
        Europe_Mariehamn,
        [Description("Europe/Minsk")]
        Europe_Minsk,
        [Description("Europe/Monaco")]
        Europe_Monaco,
        [Description("Europe/Moscow")]
        Europe_Moscow,
        [Description("Europe/Nicosia")]
        Europe_Nicosia,
        [Description("Europe/Oslo")]
        Europe_Oslo,
        [Description("Europe/Paris")]
        Europe_Paris,
        [Description("Europe/Podgorica")]
        Europe_Podgorica,
        [Description("Europe/Prague")]
        Europe_Prague,
        [Description("Europe/Riga")]
        Europe_Riga,
        [Description("Europe/Rome")]
        Europe_Rome,
        [Description("Europe/Samara")]
        Europe_Samara,
        [Description("Europe/San_Marino")]
        Europe_San_Marino,
        [Description("Europe/Sarajevo")]
        Europe_Sarajevo,
        [Description("Europe/Saratov")]
        Europe_Saratov,
        [Description("Europe/Simferopol")]
        Europe_Simferopol,
        [Description("Europe/Skopje")]
        Europe_Skopje,
        [Description("Europe/Sofia")]
        Europe_Sofia,
        [Description("Europe/Stockholm")]
        Europe_Stockholm,
        [Description("Europe/Tallinn")]
        Europe_Tallinn,
        [Description("Europe/Tirane")]
        Europe_Tirane,
        [Description("Europe/Tiraspol")]
        Europe_Tiraspol,
        [Description("Europe/Ulyanovsk")]
        Europe_Ulyanovsk,
        [Description("Europe/Uzhgorod")]
        Europe_Uzhgorod,
        [Description("Europe/Vaduz")]
        Europe_Vaduz,
        [Description("Europe/Vatican")]
        Europe_Vatican,
        [Description("Europe/Vienna")]
        Europe_Vienna,
        [Description("Europe/Vilnius")]
        Europe_Vilnius,
        [Description("Europe/Volgograd")]
        Europe_Volgograd,
        [Description("Europe/Warsaw")]
        Europe_Warsaw,
        [Description("Europe/Zagreb")]
        Europe_Zagreb,
        [Description("Europe/Zaporozhye")]
        Europe_Zaporozhye,
        [Description("Europe/Zurich")]
        Europe_Zurich,
        [Description("GMT")]
        GMT,
        [Description("Indian/Antananarivo")]
        Indian_Antananarivo,
        [Description("Indian/Chagos")]
        Indian_Chagos,
        [Description("Indian/Christmas")]
        Indian_Christmas,
        [Description("Indian/Cocos")]
        Indian_Cocos,
        [Description("Indian/Comoro")]
        Indian_Comoro,
        [Description("Indian/Kerguelen")]
        Indian_Kerguelen,
        [Description("Indian/Mahe")]
        Indian_Mahe,
        [Description("Indian/Maldives")]
        Indian_Maldives,
        [Description("Indian/Mauritius")]
        Indian_Mauritius,
        [Description("Indian/Mayotte")]
        Indian_Mayotte,
        [Description("Indian/Reunion")]
        Indian_Reunion,
        [Description("Pacific/Apia")]
        Pacific_Apia,
        [Description("Pacific/Auckland")]
        Pacific_Auckland,
        [Description("Pacific/Bougainville")]
        Pacific_Bougainville,
        [Description("Pacific/Chatham")]
        Pacific_Chatham,
        [Description("Pacific/Chuuk")]
        Pacific_Chuuk,
        [Description("Pacific/Easter")]
        Pacific_Easter,
        [Description("Pacific/Efate")]
        Pacific_Efate,
        [Description("Pacific/Enderbury")]
        Pacific_Enderbury,
        [Description("Pacific/Fakaofo")]
        Pacific_Fakaofo,
        [Description("Pacific/Fiji")]
        Pacific_Fiji,
        [Description("Pacific/Funafuti")]
        Pacific_Funafuti,
        [Description("Pacific/Galapagos")]
        Pacific_Galapagos,
        [Description("Pacific/Gambier")]
        Pacific_Gambier,
        [Description("Pacific/Guadalcanal")]
        Pacific_Guadalcanal,
        [Description("Pacific/Guam")]
        Pacific_Guam,
        [Description("Pacific/Honolulu")]
        Pacific_Honolulu,
        [Description("Pacific/Johnston")]
        Pacific_Johnston,
        [Description("Pacific/Kiritimati")]
        Pacific_Kiritimati,
        [Description("Pacific/Kosrae")]
        Pacific_Kosrae,
        [Description("Pacific/Kwajalein")]
        Pacific_Kwajalein,
        [Description("Pacific/Majuro")]
        Pacific_Majuro,
        [Description("Pacific/Marquesas")]
        Pacific_Marquesas,
        [Description("Pacific/Midway")]
        Pacific_Midway,
        [Description("Pacific/Nauru")]
        Pacific_Nauru,
        [Description("Pacific/Niue")]
        Pacific_Niue,
        [Description("Pacific/Norfolk")]
        Pacific_Norfolk,
        [Description("Pacific/Noumea")]
        Pacific_Noumea,
        [Description("Pacific/Pago_Pago")]
        Pacific_Pago_Pago,
        [Description("Pacific/Palau")]
        Pacific_Palau,
        [Description("Pacific/Pitcairn")]
        Pacific_Pitcairn,
        [Description("Pacific/Pohnpei")]
        Pacific_Pohnpei,
        [Description("Pacific/Ponape")]
        Pacific_Ponape,
        [Description("Pacific/Port_Moresby")]
        Pacific_Port_Moresby,
        [Description("Pacific/Rarotonga")]
        Pacific_Rarotonga,
        [Description("Pacific/Saipan")]
        Pacific_Saipan,
        [Description("Pacific/Samoa")]
        Pacific_Samoa,
        [Description("Pacific/Tahiti")]
        Pacific_Tahiti,
        [Description("Pacific/Tarawa")]
        Pacific_Tarawa,
        [Description("Pacific/Tongatapu")]
        Pacific_Tongatapu,
        [Description("Pacific/Truk")]
        Pacific_Truk,
        [Description("Pacific/Wake")]
        Pacific_Wake,
        [Description("Pacific/Wallis")]
        Pacific_Wallis,
        [Description("Pacific/Yap")]
        Pacific_Yap,
        [Description("UTC")]
        UTC
    }
}
